import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import "@uploadthing/react/styles.css";

export const metadata = {
  title: "Buy A Thing",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>{children}</body>
    </html>
  );
}
